export let TEXTNODE='TEXTNODE';
export let COMMENTNODE='COMMENTNODE';
export let NODESTART='NODESTART';
export let NODEEND='NODEEND';
export let NODECLOSESELF='NODECLOSESELF';
export let COMMENTSTART='COMMENTSTART';
export let COMMENTEND='COMMENTEND';